spring:
  cloud:
    zookeeper.connect-string: localhost:2181
  kafka:
    bootstrap-servers: localhost:9092
  docker.compose:
    file: dev/docker-compose.yaml
    start.command: up
    stop.command: down
