spring:
  application.name: kafka-demo-application
  cloud:
    zookeeper.connect-string: zookeeper:2181
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      spring.json.type.mapping: demo-data:artiow.examples.kafka.dto.DemoData
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: kafka-demo-group
      auto-offset-reset: latest
logging:
  pattern.console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr([${spring.application.name:-},%X{traceId:-},%X{spanId:-}]){faint} %clr(${PID}){magenta} %clr(---){faint} %clr([%30.30t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
