apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-demo-application-deployment
  labels:
    app: kafka-demo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-demo-application
  template:
    metadata:
      labels:
        app: kafka-demo-application
    spec:
      containers:
        - name: kafka-demo-application
          image: artiow/examples/kafka-demo-application:snapshot
          imagePullPolicy: IfNotPresent
          args: [
            "--spring.cloud.zookeeper.connect-string=${ZOOKEEPER_HOST}:${ZOOKEEPER_PORT}",
            "--spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}"
          ]
          ports:
            - containerPort: 8080
          env:
            - name: ZOOKEEPER_HOST
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: zookeeper-host
            - name: ZOOKEEPER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: zookeeper-port
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka-host
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka-port
