apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-demo-application-deployment
  labels:
    app: kafka-demo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-demo-application
  template:
    metadata:
      labels:
        app: kafka-demo-application
    spec:
      containers:
        - name: kafka-demo-application
          image: artiow/examples/kafka-demo-application:snapshot
          imagePullPolicy: IfNotPresent
          args: [
            "-Dspring.cloud.zookeeper.connect-string=${ZOOKEEPER_URL}",
            "-Dspring.kafka.bootstrap-servers=${KAFKA_URL}"
          ]
          ports:
            - containerPort: 8080
          env:
            - name: ZOOKEEPER_URL
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: zookeeper-url
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka-url
