version: '3.8'

services:
  kafka-demo-application:
    build: ./
    container_name: kafka-demo-application
    depends_on:
      - zookeeper
      - kafka
      - zipkin
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    tmpfs:
      # anonymous volumes creation preventing
      # (zookeeper Dockerfile has VOLUME instruction)
      - /data
      - /datalog
      - /logs
  kafka:
    image: bitnami/kafka
    container_name: kafka
    hostname: kafka
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    hostname: zipkin
